[package]
name = "example-minimal"
description = "The smallest Ferrum Alloy service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
ferrum-alloy = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
