//! `ferrum-alloy openapi export`: produces the OpenAPI artifact and detects
//! drift.
//!
//! The document comes from the project's own `openapi` binary (generated by
//! `ferrum-alloy new --with openapi`), run with `cargo run --bin openapi`
//! through an explicit argument list (no shell), or from `--input`. With
//! `--manifest`, `servers` is set to the manifest's gateway-facing
//! `public_path`, and stripped service base paths are removed from operations.
//!
//! AI-agent tool metadata (`x-ferrum-mcp`, see
//! [`ferrum_alloy_edge::agents`]): the manifest's `[agents]` section becomes
//! the document-level extension, exposed operations get their method's
//! default MCP annotations, and metadata Ferrum Edge would reject or an agent
//! could not use fails the export and `--check` with exit 3. A hand-written
//! selection that publishes every `GET` operation is a warning.

use std::path::PathBuf;
use std::process::{Command, ExitCode};

use clap::{Args, Subcommand};
use serde_json::Value;

use crate::error::CliError;
use crate::input::{ReadError, describe, invalid, read_regular_file_bounded};

/// `openapi` subcommands.
#[derive(Debug, Subcommand)]
pub(crate) enum OpenapiCommand {
    /// Export (or `--check`) the OpenAPI document.
    Export(ExportArgs),
}

/// Arguments for `openapi export`.
#[derive(Debug, Args)]
pub(crate) struct ExportArgs {
    /// Project directory containing Cargo.toml.
    #[arg(long, default_value = ".")]
    project: PathBuf,
    /// Binary that prints the document.
    #[arg(long, default_value = "openapi")]
    bin: String,
    /// Read the document from this file instead of running the project.
    #[arg(long)]
    input: Option<PathBuf>,
    /// Service manifest; sets `servers` to `api.public_path`, maps stripped base paths, and
    /// stamps `[agents]` as the document-level `x-ferrum-mcp`.
    #[arg(long)]
    manifest: Option<PathBuf>,
    /// Output file.
    #[arg(long, default_value = "openapi.json")]
    output: PathBuf,
    /// Compare with the existing output instead of writing; exit 4 on drift.
    #[arg(long)]
    check: bool,
}

const MAX_DOCUMENT_BYTES: u64 = 16 * 1024 * 1024;

fn load(args: &ExportArgs) -> Result<Vec<u8>, CliError> {
    if let Some(input) = &args.input {
        return read_regular_file_bounded(input, MAX_DOCUMENT_BYTES).map_err(|e| invalid(input, e));
    }
    if !args
        .bin
        .bytes()
        .all(|b| b.is_ascii_alphanumeric() || matches!(b, b'-' | b'_'))
    {
        return Err(CliError::Invalid(
            "--bin must be a binary target name".into(),
        ));
    }
    let manifest_path = args.project.join("Cargo.toml");
    if !manifest_path.is_file() {
        return Err(CliError::Invalid(format!(
            "{} not found",
            manifest_path.display()
        )));
    }
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    crate::eprint(&format!(
        "running: cargo run --quiet --manifest-path {} --bin {}\n",
        manifest_path.display(),
        args.bin
    ));
    let output = Command::new(cargo)
        .arg("run")
        .arg("--quiet")
        .arg("--manifest-path")
        .arg(&manifest_path)
        .arg("--bin")
        .arg(&args.bin)
        .stderr(std::process::Stdio::inherit())
        .output()
        .map_err(|e| CliError::Io(format!("cannot run cargo: {e}")))?;
    if !output.status.success() {
        return Err(CliError::Io(format!(
            "`cargo run --bin {}` failed ({})",
            args.bin, output.status
        )));
    }
    Ok(output.stdout)
}

fn validate(document: &Value) -> Result<(), CliError> {
    let version = document
        .get("openapi")
        .and_then(Value::as_str)
        .unwrap_or_default();
    if !version.starts_with("3.") {
        return Err(CliError::Invalid(format!(
            "not an OpenAPI 3.x document (openapi = {version:?}); Ferrum Nexus accepts only 3.x"
        )));
    }
    if !document.get("paths").is_some_and(Value::is_object) {
        return Err(CliError::Invalid(
            "OpenAPI document has no `paths` object".into(),
        ));
    }
    if !document.get("info").is_some_and(Value::is_object) {
        return Err(CliError::Invalid(
            "OpenAPI document has no `info` object".into(),
        ));
    }
    Ok(())
}

fn normalize_paths(
    document: &mut Value,
    manifest: &ferrum_alloy_edge::manifest::ServiceManifest,
) -> Result<(), CliError> {
    let Some(paths) = document.get_mut("paths").and_then(Value::as_object_mut) else {
        return Ok(());
    };
    if !manifest.api.strip_public_path || manifest.api.service_base_path == "/" {
        return Ok(());
    }

    let base_path = manifest.api.service_base_path.trim_end_matches('/');
    let mut normalized_paths = serde_json::Map::new();
    for (path, operations) in std::mem::take(paths) {
        let normalized = if path == base_path {
            "/"
        } else if let Some(suffix) = path.strip_prefix(base_path).filter(|s| s.starts_with('/')) {
            suffix
        } else {
            &path
        };
        if normalized_paths
            .insert(normalized.to_owned(), operations)
            .is_some()
        {
            return Err(CliError::Invalid(format!(
                "OpenAPI paths collide after removing service_base_path {base_path:?}"
            )));
        }
    }
    *paths = normalized_paths;
    Ok(())
}

/// Runs an `openapi` subcommand.
pub(crate) fn run(command: OpenapiCommand) -> Result<ExitCode, CliError> {
    let OpenapiCommand::Export(args) = command;
    let bytes = load(&args)?;
    let mut document: Value = serde_json::from_slice(&bytes)
        .map_err(|e| CliError::Invalid(format!("document is not JSON: {e}")))?;
    validate(&document)?;
    let manifest = match &args.manifest {
        Some(path) => Some(crate::edge::read_manifest(path)?),
        None => None,
    };
    if let Some(manifest) = &manifest {
        normalize_paths(&mut document, manifest)?;
        if let Some(map) = document.as_object_mut() {
            map.insert(
                "servers".into(),
                serde_json::json!([{ "url": manifest.api.public_path, "description": "Ferrum Edge public path" }]),
            );
        }
    }
    let warnings = ferrum_alloy_edge::agents::prepare(&mut document, manifest.as_ref())
        .map_err(|e| CliError::Invalid(e.to_string()))?;
    for warning in warnings {
        crate::eprint(&format!("warning: {warning}\n"));
    }
    let rendered = format!(
        "{}\n",
        serde_json::to_string_pretty(&document).map_err(|e| CliError::Io(e.to_string()))?
    );
    if args.check {
        // The existing output may be laid out differently from `rendered`,
        // which can exceed the input limit once pretty-printed.
        let limit = MAX_DOCUMENT_BYTES.max(u64::try_from(rendered.len()).unwrap_or(u64::MAX));
        let existing = match read_regular_file_bounded(&args.output, limit) {
            Ok(existing) => existing,
            Err(ReadError::Io(e)) => {
                return Err(CliError::Drift(format!(
                    "{}: {e}; run without --check to create it",
                    args.output.display()
                )));
            }
            Err(e) => return Err(CliError::Drift(describe(&args.output, e))),
        };
        let existing: Value = serde_json::from_slice(&existing)
            .map_err(|e| CliError::Drift(format!("{} is not JSON: {e}", args.output.display())))?;
        if existing != document {
            return Err(CliError::Drift(format!(
                "{} is out of date with the code; run `ferrum-alloy openapi export` and commit the result",
                args.output.display()
            )));
        }
        crate::print(&format!("{} is up to date\n", args.output.display()))?;
        return Ok(ExitCode::SUCCESS);
    }
    crate::fsout::write_atomically(
        &args.output,
        rendered.as_bytes(),
        crate::fsout::NewFileMode::Umask,
    )?;
    crate::eprint(&format!("wrote {}\n", args.output.display()));
    Ok(ExitCode::SUCCESS)
}
