//! RFC 9457 Problem Details.
//!
//! Every framework-generated error uses `application/problem+json`, a stable
//! problem type, the correct status, and a sanitized `detail`. Application
//! handlers may return [`Problem`] too. Alloy never rewrites response bodies
//! that an application produced.
//!
//! Problem type URIs are `tag:` URIs (RFC 4151). They are stable identifiers
//! and are not meant to be dereferenced.

use std::collections::BTreeMap;

use axum::response::{IntoResponse, Response};
use http::StatusCode;
use http::header::{CONTENT_TYPE, HeaderValue};
use serde::Serialize;
use serde_json::Value;

/// The `application/problem+json` media type.
pub const PROBLEM_JSON: &str = "application/problem+json";

/// Prefix of Alloy's problem type URIs.
pub const TYPE_PREFIX: &str = "tag:ferrumedge.com,2026:alloy/problem/";

/// Maximum length of a framework-generated `detail`.
const MAX_DETAIL: usize = 256;

/// Problem types generated by Alloy itself.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProblemKind {
    /// The body is not syntactically valid JSON.
    MalformedJson,
    /// The body is JSON but does not match the expected shape.
    InvalidBody,
    /// The `Content-Type` is not supported.
    UnsupportedMediaType,
    /// The body exceeds the configured limit.
    PayloadTooLarge,
    /// Path parameters could not be parsed.
    InvalidPathParameters,
    /// The query string could not be parsed.
    InvalidQuery,
    /// Application-level validation failed.
    ValidationFailed,
    /// No route matches the path.
    RouteNotFound,
    /// The route exists but not for this method.
    MethodNotAllowed,
    /// Authentication is missing or invalid.
    Unauthorized,
    /// Authenticated but not permitted.
    Forbidden,
    /// Credentials could not be checked because the key source is unavailable.
    AuthUnavailable,
    /// The admission limit was reached.
    Overloaded,
    /// The client or listener exceeded its request rate limit.
    RateLimited,
    /// Response headers were not produced within the deadline.
    RequestTimeout,
    /// The service is draining for shutdown.
    Draining,
    /// The request did not come from a required gateway identity.
    GatewayRequired,
    /// An unexpected internal error.
    Internal,
}

impl ProblemKind {
    /// Stable slug used in the type URI.
    pub fn slug(self) -> &'static str {
        match self {
            Self::MalformedJson => "malformed-json",
            Self::InvalidBody => "invalid-body",
            Self::UnsupportedMediaType => "unsupported-media-type",
            Self::PayloadTooLarge => "payload-too-large",
            Self::InvalidPathParameters => "invalid-path-parameters",
            Self::InvalidQuery => "invalid-query",
            Self::ValidationFailed => "validation-failed",
            Self::RouteNotFound => "route-not-found",
            Self::MethodNotAllowed => "method-not-allowed",
            Self::Unauthorized => "unauthorized",
            Self::Forbidden => "forbidden",
            Self::AuthUnavailable => "auth-unavailable",
            Self::Overloaded => "overloaded",
            Self::RateLimited => "rate-limited",
            Self::RequestTimeout => "request-timeout",
            Self::Draining => "draining",
            Self::GatewayRequired => "gateway-required",
            Self::Internal => "internal",
        }
    }

    /// HTTP status.
    pub fn status(self) -> StatusCode {
        match self {
            Self::MalformedJson | Self::InvalidPathParameters | Self::InvalidQuery => {
                StatusCode::BAD_REQUEST
            }
            Self::InvalidBody | Self::ValidationFailed => StatusCode::UNPROCESSABLE_ENTITY,
            Self::UnsupportedMediaType => StatusCode::UNSUPPORTED_MEDIA_TYPE,
            Self::PayloadTooLarge => StatusCode::PAYLOAD_TOO_LARGE,
            Self::RouteNotFound => StatusCode::NOT_FOUND,
            Self::MethodNotAllowed => StatusCode::METHOD_NOT_ALLOWED,
            Self::RateLimited => StatusCode::TOO_MANY_REQUESTS,
            Self::Unauthorized => StatusCode::UNAUTHORIZED,
            Self::Forbidden | Self::GatewayRequired => StatusCode::FORBIDDEN,
            Self::Overloaded | Self::RequestTimeout | Self::Draining | Self::AuthUnavailable => {
                StatusCode::SERVICE_UNAVAILABLE
            }
            Self::Internal => StatusCode::INTERNAL_SERVER_ERROR,
        }
    }

    /// Short human-readable title.
    pub fn title(self) -> &'static str {
        match self {
            Self::MalformedJson => "Malformed JSON",
            Self::InvalidBody => "Invalid request body",
            Self::UnsupportedMediaType => "Unsupported media type",
            Self::PayloadTooLarge => "Payload too large",
            Self::InvalidPathParameters => "Invalid path parameters",
            Self::InvalidQuery => "Invalid query string",
            Self::ValidationFailed => "Validation failed",
            Self::RouteNotFound => "Not found",
            Self::MethodNotAllowed => "Method not allowed",
            Self::Unauthorized => "Unauthorized",
            Self::Forbidden => "Forbidden",
            Self::AuthUnavailable => "Authentication unavailable",
            Self::Overloaded => "Service overloaded",
            Self::RateLimited => "Too many requests",
            Self::RequestTimeout => "Request timed out",
            Self::Draining => "Service is shutting down",
            Self::GatewayRequired => "Gateway required",
            Self::Internal => "Internal server error",
        }
    }

    /// The full type URI.
    pub fn type_uri(self) -> String {
        format!("{TYPE_PREFIX}{}", self.slug())
    }
}

/// The serialized members of a problem.
#[derive(Debug, Clone, PartialEq, Serialize)]
struct Body {
    #[serde(rename = "type")]
    type_uri: String,
    title: String,
    status: u16,
    #[serde(skip_serializing_if = "Option::is_none")]
    detail: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    instance: Option<String>,
    #[serde(flatten)]
    extensions: BTreeMap<String, Value>,
    #[serde(skip)]
    headers: Vec<(http::HeaderName, HeaderValue)>,
}

/// An RFC 9457 problem. Boxed so `Result<T, Problem>` stays small.
#[derive(Debug, Clone, PartialEq)]
pub struct Problem(Box<Body>);

impl Serialize for Problem {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        self.0.serialize(serializer)
    }
}

impl Problem {
    /// A framework problem of `kind`.
    pub fn new(kind: ProblemKind) -> Self {
        Self::custom(kind.type_uri(), kind.title(), kind.status())
    }

    /// An application-defined problem type.
    pub fn custom(
        type_uri: impl Into<String>,
        title: impl Into<String>,
        status: StatusCode,
    ) -> Self {
        Self(Box::new(Body {
            type_uri: type_uri.into(),
            title: title.into(),
            status: status.as_u16(),
            detail: None,
            instance: None,
            extensions: BTreeMap::new(),
            headers: Vec::new(),
        }))
    }

    /// Sets `detail`. Framework code passes sanitized text only.
    #[must_use]
    pub fn with_detail(mut self, detail: impl Into<String>) -> Self {
        self.0.detail = Some(detail.into());
        self
    }

    /// Sets `instance`.
    #[must_use]
    pub fn with_instance(mut self, instance: impl Into<String>) -> Self {
        self.0.instance = Some(instance.into());
        self
    }

    /// Adds an extension member. Reserved member names are ignored.
    #[must_use]
    pub fn with_extension(mut self, key: impl Into<String>, value: impl Into<Value>) -> Self {
        let key = key.into();
        if !matches!(
            key.as_str(),
            "type" | "title" | "status" | "detail" | "instance"
        ) {
            self.0.extensions.insert(key, value.into());
        }
        self
    }

    /// Adds a response header (for example `WWW-Authenticate` or `Allow`).
    #[must_use]
    pub fn with_header(mut self, name: http::HeaderName, value: HeaderValue) -> Self {
        self.0.headers.push((name, value));
        self
    }

    /// Replaces the status.
    #[must_use]
    pub fn with_status(mut self, status: StatusCode) -> Self {
        self.0.status = status.as_u16();
        self
    }

    /// The problem type URI.
    pub fn type_uri(&self) -> &str {
        &self.0.type_uri
    }

    /// The title.
    pub fn title(&self) -> &str {
        &self.0.title
    }

    /// The detail, if any.
    pub fn detail(&self) -> Option<&str> {
        self.0.detail.as_deref()
    }

    /// An extension member.
    pub fn extension(&self, key: &str) -> Option<&Value> {
        self.0.extensions.get(key)
    }

    /// The status as a `StatusCode`.
    pub fn status_code(&self) -> StatusCode {
        StatusCode::from_u16(self.0.status).unwrap_or(StatusCode::INTERNAL_SERVER_ERROR)
    }
}

impl From<ProblemKind> for Problem {
    fn from(kind: ProblemKind) -> Self {
        Self::new(kind)
    }
}

impl IntoResponse for Problem {
    fn into_response(self) -> Response {
        let status = self.status_code();
        let body = serde_json::to_vec(&self).unwrap_or_else(|_| {
            br#"{"type":"about:blank","title":"Internal server error","status":500}"#.to_vec()
        });
        let mut response = (status, body).into_response();
        response
            .headers_mut()
            .insert(CONTENT_TYPE, HeaderValue::from_static(PROBLEM_JSON));
        for (name, value) in self.0.headers {
            response.headers_mut().append(name, value);
        }
        response
    }
}

/// Makes parser output safe to return: control characters removed, length
/// bounded. Parser messages describe the client's own input, never server
/// state.
pub(crate) fn sanitize_detail(text: &str) -> String {
    let cleaned: String = text
        .chars()
        .map(|c| if c.is_control() { ' ' } else { c })
        .collect();
    if cleaned.len() <= MAX_DETAIL {
        return cleaned;
    }
    let mut end = MAX_DETAIL;
    while !cleaned.is_char_boundary(end) {
        end -= 1;
    }
    format!("{}…", &cleaned[..end])
}
